### PR TITLE
SGF-845 - Fix ContinuousQueryListenerContainerTests

### PR DESCRIPTION
**Pull request by jujoramos**
Mock PoolImpl instead of Pool to prevent a ClassCast in the tests.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jujoramos Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-gemfire&pullRequestId=126)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-gemfire&pullRequestId=126) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jujoramos Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-gemfire&pullRequestId=126)!

**Comment by jxblum** [comment]
2 things:

1. When writing _Unit Tests_ and mocking the collaborators for the _Subject Under Test_ (SUT), it is uncommon to mock the actual implementing class of the collaborators used by the SUT (e.g. In this case, SDG's `ContinuousQueryListenerContainer` class's use of a Geode `Pool` instance).

Rather, in the spirit of "_coding to interfaces_", the SUT should only ever refer to and use an instance of a `Pool` by the `Pool` interface.  That is indeed what the SDG `ContinuousQueryListenerContainer` class does.  In fact, most of SDG adheres to, and only uses Geode interfaces for Geode objects.  There are few Exceptions here and there because the intended functionality is not appropriately exposed in a Geode interface.

2. Geode's `PoolManager` naively assumes all `Pool` instances managed by the `PoolManager` are Geode `PoolImpl` objects, for which I have filed a bug for in Apache Geode [GEODE-7159](https://issues.apache.org/jira/browse/GEODE-7159).

One of the development tasks I am hoping to accomplish by/during _Spring Data_ **Neuman**/`2.3` for SDG, will be to replace SDG's existing [test framework](https://github.com/spring-projects/spring-data-gemfire/tree/master/src/test/java/org/springframework/data/gemfire/test) with _**Spring Test for Apache Geode**_ ([STDG](https://github.com/spring-projects/spring-test-data-geode)).

Indeed, the existing test framework bits in SDG formed the foundation for the STDG project itself, which is used by SBDG and SSDG, extensively.  I just need to go back an retrofit SDG's supporting test infrastructure to use STDG now.

One of the many things STDG needed to handle and account for properly was in fact [GEODE-7159](https://issues.apache.org/jira/browse/GEODE-7159), particularly when a "mock" `Pool` gets registered with Apache Geode's `PoolManager`, which is required in some test cases for SDG, SSDG and SBDG.  STDG now contains [special logic](https://github.com/spring-projects/spring-test-data-geode/commit/b5f0bf1e09ab77b80ae865a36878104806e8f9dc) to avoid the `ClassCastException` to what you alluded to above, even when a mock `Pool` is registered with the `PoolManager`.  This [test class](https://github.com/spring-projects/spring-test-data-geode/blob/master/spring-data-geode-test/src/test/java/org/springframework/data/gemfire/tests/MockClientCacheDefaultPoolRegisteredWithPoolManagerUnitTests.java) tests that very thing, particularly when the `PoolManager.close()` method is invoked, which gets called by the test class indirectly [here](https://github.com/spring-projects/spring-test-data-geode/blob/master/spring-data-geode-test/src/test/java/org/springframework/data/gemfire/tests/MockClientCacheDefaultPoolRegisteredWithPoolManagerUnitTests.java#L80), then [here](https://github.com/spring-projects/spring-test-data-geode/blob/master/spring-data-geode-test/src/main/java/org/springframework/data/gemfire/tests/mock/GemFireMockObjectsSupport.java#L283-L284) and specifically, [here](https://github.com/spring-projects/spring-test-data-geode/blob/master/spring-data-geode-test/src/main/java/org/springframework/data/gemfire/tests/mock/GemFireMockObjectsSupport.java#L298).  It is `PoolManager.close()` that naively assumes all `Pool` objects are `PoolImpl` objects, thereby causing the `ClassCastException`, which is why STDG is [careful](https://github.com/spring-projects/spring-test-data-geode/blob/master/spring-data-geode-test/src/main/java/org/springframework/data/gemfire/tests/mock/GemFireMockObjectsSupport.java#L321-L329) to make sure all (framework) "managed" `Pool` objects properly cleaned up before `PoolManager.close()` is called.


Anyway, given the information above, I will not be merging this PR.

Thank you for your contribution.

**Comment by jujoramos** [comment]
👍

**Pull request closed without merging**
